/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.FuncionarioDAO;
import Models.Departamento;
import Models.Funcionario;
import TableModels.ListaDepartamentosTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jhonn
 */
public class EditaFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form EditaFuncionario
     */
    ListaDepartamentosTableModel tableModel = new ListaDepartamentosTableModel();
    
    public EditaFuncionario(Funcionario funcionario) {
        initComponents();
        tableDepartamentos.setModel(tableModel);
        tableModel.listar();
        inputNome.setText(funcionario.getNome());
        inputSobrenome.setText(funcionario.getSobrenome());
        inputRg.setText(funcionario.getRg());
        inputCpf.setText(funcionario.getCpf());
        inputTelefone.setText(funcionario.getTelefone());
        inputSenha.setText(funcionario.getSenha());
        inputSalario.setText(String.valueOf(funcionario.getSalario()));
        comboNivel.setSelectedIndex(funcionario.getNivel()-1);
        inputId.setText(String.valueOf(funcionario.getId()));
    }

    private EditaFuncionario() {
        initComponents();
        tableDepartamentos.setModel(tableModel);
        tableModel.listar();
    }
    
    private boolean dadosValidos(){
        if (inputNome.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Insira o nome");
            return false;
        }
        if (inputSobrenome.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Insira o sobrenome");
            return false;
        }
        if (inputRg.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Insira o RG");
            return false;
        }
        if (inputCpf.getText().replaceAll("[-. ]", "").length() < 11){
            JOptionPane.showMessageDialog(null, "Insira o CPF");
            return false;
        }
        if (inputTelefone.getText().replaceAll("[-. ]", "").length() < 10){
            JOptionPane.showMessageDialog(null, "Insira o telefone");
            return false;
        }
        if (tableDepartamentos.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Selecione um departamento");
            return false;
        }
        if (inputSalario.getText().equals("") || Double.parseDouble(inputSalario.getText()) < 1000){
            JOptionPane.showMessageDialog(null, "O salario mínimo é 1000 reais.");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputNome = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        labelSobrenome = new javax.swing.JLabel();
        inputSobrenome = new javax.swing.JTextField();
        labelRg = new javax.swing.JLabel();
        inputRg = new javax.swing.JTextField();
        labelCpf = new javax.swing.JLabel();
        inputCpf = new javax.swing.JFormattedTextField();
        labelTelefone = new javax.swing.JLabel();
        inputTelefone = new javax.swing.JFormattedTextField();
        labelSenha = new javax.swing.JLabel();
        inputSenha = new javax.swing.JPasswordField();
        labelSalario = new javax.swing.JLabel();
        inputSalario = new javax.swing.JTextField();
        labelNivel = new javax.swing.JLabel();
        comboNivel = new javax.swing.JComboBox<>();
        labelDepartamento = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDepartamentos = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        inputId = new javax.swing.JTextField();
        labelNivel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputNome.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        labelNome.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelNome.setText("Nome");

        labelSobrenome.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelSobrenome.setText("Sobrenome");

        inputSobrenome.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        labelRg.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelRg.setText("RG");

        inputRg.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        labelCpf.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelCpf.setText("CPF");

        try {
            inputCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inputCpf.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        labelTelefone.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelTelefone.setText("Telefone");

        try {
            inputTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inputTelefone.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        labelSenha.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelSenha.setText("Senha");

        inputSenha.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        labelSalario.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelSalario.setText("Salario");

        inputSalario.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        labelNivel.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelNivel.setText("Nivel");

        comboNivel.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        comboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        labelDepartamento.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelDepartamento.setText("Departamento");

        tableDepartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableDepartamentos);

        btnSalvar.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        inputId.setEditable(false);

        labelNivel1.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelNivel1.setText("#");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(520, 520, 520)
                        .addComponent(btnSalvar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelRg)
                                    .addComponent(labelNome)
                                    .addComponent(labelTelefone)
                                    .addComponent(labelSalario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputRg, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSobrenome)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelCpf, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(labelSenha)
                                                .addGap(7, 7, 7)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(inputSobrenome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputCpf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNivel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelNivel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDepartamento)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNome)
                            .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNivel)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelNivel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRg)
                            .addComponent(inputRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDepartamento))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTelefone)
                            .addComponent(inputTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSalario)
                            .addComponent(inputSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSobrenome)
                            .addComponent(inputSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCpf)
                            .addComponent(inputCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSenha)
                            .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (dadosValidos()){
            Departamento departamento = tableModel.buscaDepartamento(tableDepartamentos.getSelectedRow());
            Funcionario funcionario = new Funcionario(inputSenha.getText(), Double.parseDouble(inputSalario.getText()), Integer.parseInt((String) comboNivel.getSelectedItem()), departamento, inputNome.getText(), inputSobrenome.getText(), inputRg.getText(), inputCpf.getText(), inputTelefone.getText());
            funcionario.setId(Integer.parseInt(inputId.getText()));
            FuncionarioDAO dao = new FuncionarioDAO();
            if (dao.atualizar(funcionario)){
                JOptionPane.showMessageDialog(null, "Funcionario atualizado com sucesso.");
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> comboNivel;
    private javax.swing.JFormattedTextField inputCpf;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputRg;
    private javax.swing.JTextField inputSalario;
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JTextField inputSobrenome;
    private javax.swing.JFormattedTextField inputTelefone;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelDepartamento;
    private javax.swing.JLabel labelNivel;
    private javax.swing.JLabel labelNivel1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelRg;
    private javax.swing.JLabel labelSalario;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelSobrenome;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JTable tableDepartamentos;
    // End of variables declaration//GEN-END:variables
}
