/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.AnalistaDAO;
import DAO.DepartamentoDAO;
import DAO.DiretorDAO;
import DAO.GerenteDAO;
import DAO.LimpezaDAO;
import DAO.ProgramadorDAO;
import Models.Analista;
import Models.Departamento;
import Models.Diretor;
import Models.Funcionario;
import Models.Gerente;
import Models.Limpeza;
import Models.Programador;
import TableModels.ListaDepartamentosTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhonny
 */
public class NovoFuncionario extends javax.swing.JFrame {

    ListaDepartamentosTableModel tableModel = new ListaDepartamentosTableModel();
    ListaDepartamentosTableModel tableModelDepartamentosGerenciados = new ListaDepartamentosTableModel();
    
    public NovoFuncionario() {
        initComponents();
        tableDepartamentos.setModel(tableModel);
        tableDepartamentosGerenciados.setModel(tableModelDepartamentosGerenciados);
        tableModel.listar();
        escondeOpcoes();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelNome = new javax.swing.JLabel();
        labelSobrenome = new javax.swing.JLabel();
        labelRg = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        labelNivel = new javax.swing.JLabel();
        labelSalario = new javax.swing.JLabel();
        labelCargo = new javax.swing.JLabel();
        labelDepartamento = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        inputRg = new javax.swing.JTextField();
        inputSobrenome = new javax.swing.JTextField();
        inputSenha = new javax.swing.JPasswordField();
        inputTelefone = new javax.swing.JFormattedTextField();
        comboNivel = new javax.swing.JComboBox<>();
        comboCargo = new javax.swing.JComboBox<>();
        inputCpf = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDepartamentos = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        inputSalario = new javax.swing.JTextField();
        labelDepartamentoGerenciado = new javax.swing.JLabel();
        comboDepartamentoGerenciado = new javax.swing.JComboBox<>();
        labelDepartamentosGerenciados = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableDepartamentosGerenciados = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelNome.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelNome.setText("Nome");

        labelSobrenome.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelSobrenome.setText("Sobrenome");

        labelRg.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelRg.setText("RG");

        labelCpf.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelCpf.setText("CPF");

        labelSenha.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelSenha.setText("Senha");

        labelTelefone.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelTelefone.setText("Telefone");

        labelNivel.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelNivel.setText("Nivel");

        labelSalario.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelSalario.setText("Salario");

        labelCargo.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelCargo.setText("Cargo");

        labelDepartamento.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelDepartamento.setText("Departamento");

        inputNome.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        inputRg.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        inputSobrenome.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        inputSenha.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        try {
            inputTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inputTelefone.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        comboNivel.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        comboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        comboCargo.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        comboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auxiliar de Limpeza", "Programador", "Analista", "Gerente", "Diretor" }));
        comboCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCargoActionPerformed(evt);
            }
        });

        try {
            inputCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inputCpf.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        tableDepartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableDepartamentos);

        btnSalvar.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        inputSalario.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        labelDepartamentoGerenciado.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelDepartamentoGerenciado.setText("Departamento Gerenciado");

        comboDepartamentoGerenciado.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        labelDepartamentosGerenciados.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelDepartamentosGerenciados.setText("Departamentos Gerenciados");

        tableDepartamentosGerenciados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tableDepartamentosGerenciados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelRg)
                    .addComponent(labelNome)
                    .addComponent(labelTelefone)
                    .addComponent(labelSalario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputRg, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDepartamentoGerenciado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboDepartamentoGerenciado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(labelSobrenome))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCpf, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelNivel)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelCargo)
                                                    .addComponent(labelSenha))
                                                .addGap(7, 7, 7)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))))
                    .addComponent(inputSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDepartamento))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(btnSalvar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(labelDepartamentosGerenciados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputSobrenome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addComponent(inputCpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addComponent(inputSenha, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comboCargo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboNivel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSobrenome)
                    .addComponent(inputSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRg)
                    .addComponent(labelCpf)
                    .addComponent(inputCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefone)
                    .addComponent(inputTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSenha)
                    .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSalario)
                    .addComponent(inputSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCargo)
                    .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDepartamento)
                    .addComponent(labelNivel)
                    .addComponent(comboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDepartamentoGerenciado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboDepartamentoGerenciado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDepartamentosGerenciados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (dadosValidos()){
            Departamento departamento = tableModel.buscaDepartamento(tableDepartamentos.getSelectedRow());
            if ("Auxiliar de Limpeza".equals((String) comboCargo.getSelectedItem())){
                Limpeza limpeza = new Limpeza(Double.parseDouble(inputSalario.getText()), Integer.parseInt((String) comboNivel.getSelectedItem()), departamento, inputNome.getText(), inputSobrenome.getText(), inputRg.getText(), inputCpf.getText(), inputTelefone.getText());
                LimpezaDAO dao = new LimpezaDAO();
                if (dao.inserir(limpeza)){
                    JOptionPane.showMessageDialog(null, "Funcionario inserido com sucesso.");
                    this.dispose();
                }
            } else if ("Programador".equals((String) comboCargo.getSelectedItem())){
                Programador programador = new Programador(inputSenha.getText(), Double.parseDouble(inputSalario.getText()), Integer.parseInt((String) comboNivel.getSelectedItem()), departamento, inputNome.getText(), inputSobrenome.getText(), inputRg.getText(), inputCpf.getText(), inputTelefone.getText());
                ProgramadorDAO dao = new ProgramadorDAO();
                if (dao.inserir(programador)){
                    JOptionPane.showMessageDialog(null, "Funcionario inserido com sucesso.");
                    this.dispose();
                }
            } else if ("Analista".equals((String) comboCargo.getSelectedItem())){
                Analista analista = new Analista(inputSenha.getText(), Double.parseDouble(inputSalario.getText()), Integer.parseInt((String) comboNivel.getSelectedItem()), departamento, inputNome.getText(), inputSobrenome.getText(), inputRg.getText(), inputCpf.getText(), inputTelefone.getText());
                AnalistaDAO dao = new AnalistaDAO();
                if (dao.inserir(analista)){
                    JOptionPane.showMessageDialog(null, "Funcionario inserido com sucesso.");
                    this.dispose();
                }
            } else if ("Gerente".equals((String) comboCargo.getSelectedItem())){
                Departamento departamentoGerenciado = (Departamento) comboDepartamentoGerenciado.getSelectedItem();
                Gerente gerente = new Gerente(departamentoGerenciado, inputSenha.getText(), Double.parseDouble(inputSalario.getText()), Integer.parseInt((String) comboNivel.getSelectedItem()), departamento, inputNome.getText(), inputSobrenome.getText(), inputRg.getText(), inputCpf.getText(), inputTelefone.getText());
                GerenteDAO dao = new GerenteDAO();
                if (dao.inserir(gerente)){
                    JOptionPane.showMessageDialog(null, "Funcionario inserido com sucesso.");
                    this.dispose();
                }
            } else if ("Diretor".equals((String) comboCargo.getSelectedItem())){
                List<Departamento> departamentosGerenciados = new ArrayList();
                for (int i: tableDepartamentosGerenciados.getSelectedRows()){
                    Departamento departamentoGerenciado = tableModel.buscaDepartamento(i);
                    departamentosGerenciados.add(departamentoGerenciado);
                }
                Diretor diretor = new Diretor(departamentosGerenciados, inputSenha.getText(), Double.parseDouble(inputSalario.getText()), Integer.parseInt((String) comboNivel.getSelectedItem()), departamento, inputNome.getText(), inputSobrenome.getText(), inputRg.getText(), inputCpf.getText(), inputTelefone.getText());
                DiretorDAO dao = new DiretorDAO();
                if (dao.inserir(diretor)){
                    JOptionPane.showMessageDialog(null, "Funcionario inserido com sucesso.");
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void comboCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCargoActionPerformed
        escondeOpcoes();
        if (((String) comboCargo.getSelectedItem()).equals("Gerente")){
            DepartamentoDAO departamentoDAO = new DepartamentoDAO();
            for (Departamento d: departamentoDAO.listar()){
                comboDepartamentoGerenciado.addItem(d);
            }
            labelDepartamentoGerenciado.setVisible(true);
            comboDepartamentoGerenciado.setVisible(true);
        }
        if (((String) comboCargo.getSelectedItem()).equals("Diretor")){
            DepartamentoDAO departamentoDAO = new DepartamentoDAO();
            tableModelDepartamentosGerenciados.listar();
            labelDepartamentosGerenciados.setVisible(true);
            tableDepartamentosGerenciados.setVisible(true);
        }
    }//GEN-LAST:event_comboCargoActionPerformed

    public void escondeOpcoes(){
        labelDepartamentoGerenciado.setVisible(false);
        comboDepartamentoGerenciado.setVisible(false);
        labelDepartamentosGerenciados.setVisible(false);
        tableDepartamentosGerenciados.setVisible(false);
    }
    
    private boolean dadosValidos(){
        if (inputNome.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Insira o nome");
            return false;
        }
        if (inputSobrenome.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Insira o sobrenome");
            return false;
        }
        if (inputRg.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Insira o RG");
            return false;
        }
        if (inputCpf.getText().replaceAll("[-. ]", "").length() < 11){
            JOptionPane.showMessageDialog(null, "Insira o CPF");
            return false;
        }
        if (inputTelefone.getText().replaceAll("[-. ]", "").length() < 10){
            JOptionPane.showMessageDialog(null, "Insira o telefone");
            return false;
        }
        if (!("Auxiliar de Limpeza".equals((String) comboCargo.getSelectedItem())) && inputSenha.getText().length() < 6){
            JOptionPane.showMessageDialog(null, "A senha é obrigatória e deve ter no mínimo 6 caracteres");
            return false;
        }
        if (tableDepartamentos.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Selecione um departamento");
            return false;
        }
        if (inputSalario.getText().equals("") || Double.parseDouble(inputSalario.getText()) < 1000){
            JOptionPane.showMessageDialog(null, "O salario mínimo é 1000 reais.");
            return false;
        }
        if (("Diretor".equals((String) comboCargo.getSelectedItem())) && tableDepartamentosGerenciados.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "O diretor deve gerir no mínimo um departamento");
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> comboCargo;
    private javax.swing.JComboBox<Object> comboDepartamentoGerenciado;
    private javax.swing.JComboBox<String> comboNivel;
    private javax.swing.JFormattedTextField inputCpf;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputRg;
    private javax.swing.JTextField inputSalario;
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JTextField inputSobrenome;
    private javax.swing.JFormattedTextField inputTelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelDepartamento;
    private javax.swing.JLabel labelDepartamentoGerenciado;
    private javax.swing.JLabel labelDepartamentosGerenciados;
    private javax.swing.JLabel labelNivel;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelRg;
    private javax.swing.JLabel labelSalario;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelSobrenome;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JTable tableDepartamentos;
    private javax.swing.JTable tableDepartamentosGerenciados;
    // End of variables declaration//GEN-END:variables
}
